server:
  port: 8098


logging:
  file:
    #日志存放目录
    path: logs
    name: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/course?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&characterEncoding=UTF8

mybatis:
  #别名包
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*
